---
## Deploy Jenkins

# create project
- name: check if jenkins project {{ project_name }} exists
  shell: "{{ openshift_cli }} get project {{ project_name }}"
  register: jenkins_project_result
  ignore_errors: true
  changed_when: false

- name: create jenkins project {{ project_name }}
  shell: "{{ openshift_cli }} new-project {{ project_name }} --display-name='{{ project_display_name }}' --description='{{ project_desc }}'"
  when: jenkins_project_result|failed

- name: assign user as project admin
  shell: "{{ openshift_cli }} adm policy add-role-to-user admin {{ project_admin }} -n {{ project_name }}"
  ignore_errors: true
  when:
    - jenkins_project_result|failed
    - project_admin is defined
    - project_admin is not none
    - project_admin|trim() != ""

- name: annotate jenkins project {{ project_name }}
  shell: "{{ openshift_cli }} annotate --overwrite namespace {{ project_name }} {{ project_annotations }}"
  ignore_errors: true
  when:
    - jenkins_project_result|failed
    - project_annotations is defined
    - project_annotations is not none
    - project_annotations|trim() != ""

# deploy jenkins
- name: check if jenkins exists
  shell: "{{ openshift_cli }} get service {{ jenkins_service_name }} -n {{ project_name }}"
  register: install_jenkins
  ignore_errors: true
  changed_when: false

- name: import jenkins image tag {{ jenkins_image_tag }}
  shell: "{{ openshift_cli }} import-image jenkins:{{ jenkins_image_tag }} --from='{{ jenkins_image_repository }}:{{ jenkins_image_tag }}' --confirm -n openshift"
  ignore_errors: true
  when: >
    install_jenkins|failed and 
    jenkins_image_tag != 'latest' and
    jenkins_image_force_import

- name: deploy jenkins persistent from template
  shell: "{{ openshift_cli }} new-app jenkins-persistent -l app=jenkins -p JENKINS_SERVICE_NAME={{ jenkins_service_name }} -p JENKINS_IMAGE_STREAM_TAG=jenkins:{{ jenkins_image_tag }} -p MEMORY_LIMIT=1Gi -n {{ project_name }}"
  when: install_jenkins|failed and not ephemeral

- name: deploy jenkins ephemeral from template
  shell: "{{ openshift_cli }} new-app jenkins-ephemeral -l app=jenkins -p JENKINS_SERVICE_NAME={{ jenkins_service_name }} -p JENKINS_IMAGE_STREAM_TAG=jenkins:{{ jenkins_image_tag }} -p MEMORY_LIMIT=1Gi -n {{ project_name }}"
  when: install_jenkins|failed and ephemeral

- name: set jenkins cpu and mem resources
  shell: "{{ openshift_cli }} set resources dc/{{ jenkins_service_name }} --limits=cpu={{ jenkins_max_cpu }},memory={{ jenkins_max_mem }} --requests=cpu={{ jenkins_min_cpu }},memory={{ jenkins_min_mem }} -n {{ project_name }}"
  when: install_jenkins|failed
